---
- name: Install and configure Apache, PHP, and PostgreSQL
  hosts: {{IP2}}
  become: yes
  become_method: sudo

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install psycopg2 on Debian
      become: yes
      apt:
        name: python3-psycopg2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install PostgreSQL Client
      apt:
        name: postgresql-client
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install PHP8.2 and required extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php8.2
        - php8.2-cli
        - php8.2-pgsql  # PostgreSQL extension for PHP
      when: ansible_os_family == 'Debian'

    - name: Copy the file to /var/www/html
      ansible.builtin.copy:
        src: /home/vagrant/config/index.php
        dest: /var/www/html/index.php
      register: copy_result

    - name: Change the owner and group of the file
      ansible.builtin.file:
        path: /var/www/html/index.php
        owner: www-data
        group: www-data
        state: file
      when: copy_result.changed

    - name: Wait for PostgreSQL to be ready
      wait_for:
        host: {{IP3}}
        port: 5432  # PostgreSQL default port
        timeout: 300  # Adjust timeout as needed
      when: ansible_os_family == 'Debian'

    - name: Set PostgreSQL client user password
      shell: |
        PGPASSWORD=ChuckIsGreat543 psql -U postgres -h {{IP3}} -d postgres -c "ALTER USER postgres PASSWORD 'ChuckIsGreat543';"
      when: ansible_os_family == 'Debian'
