---
- name: Configure PostgreSQL to allow remote connections
  hosts: {{IP3}}
  become: yes

  tasks:
    - name: Update PostgreSQL configuration
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: 'listen_addresses = "*"'
      notify:
        - restart postgresql

    - name: Add remote connection rule to pg_hba.conf
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        line: 'host all all 192.168.0.0/16 md5'
      notify:
        - restart postgresql

  handlers:
    - name: restart postgresql
      service:
        name: postgresql-15  # Adjust the service name as needed for your system
        state: restarted
