---
- name: Install PostgreSQL with predefined root password
  hosts: {{IP3}}
  become: yes

  tasks:
    - name: Install psycopg2 on Debian
      apt:
        name: python3-psycopg2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install PostgreSQL Server (Debian)
      apt:
        name: postgresql-15
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install PostgreSQL Client (Debian)
      apt:
        name: postgresql-client-15
        state: present
      when: ansible_os_family == 'Debian'

    - name: Set PostgreSQL Root Password
      postgresql_user:
        db: postgres
        name: postgres
        password: ChuckIsGreat543
        encrypted: yes
        state: present
      become_user: postgres
      become: yes
      become_method: sudo
      vars:
        ansible_become_password: vagrant
