# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "httpd" do |httpd|
    httpd.vm.box = "jaca1805/debian12"
    httpd.vm.network "private_network", ip: "{{IP1}}"

    httpd.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  config.vm.define "api" do |api|
    api.vm.box = "jaca1805/debian12"
    api.vm.network "private_network", ip: "{{IP2}}"

    api.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "jaca1805/debian12"
    db.vm.network "private_network", ip: "{{IP3}}"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

end
